### PR TITLE
 Added global config pyproject.toml #52 

### PR DESCRIPTION
**Pull request by dabauxi**
This should resolve the following issues raised in https://github.com/myint/docformatter/pull/52#issuecomment-751498406
`pylint` findings were suppressed.

 * Running `docformatter` with no options doesn't work like it used to. It ought to print out a help message, but now it outputs a badly formatted line. I'd prefer the new functionality not degrade the existing use cases.
 *  The linters (`pydocstyle`, `pycodestyle`, etc.) don't pass . The `pylint` findings could be suppressed if you want though. Run `make` to see the errors.

### CODE REVIEW

**Comment by PhilReinhold** [comment]
It would be great to have this merged. The ability to configure docformatter from a project file (even better pyproject.toml, which is existing for anyone using black) is critical when trying to use it as part of project contribution standards.

**Comment by ruohola** [comment]
Any update on this?

**Comment by fmigneault** [comment]
I would like to know if there is an update on this?
Also, is it possible to provide a ``--config`` option to pass another path? 
I don't think the enforced `config_args = _read_config("pyproject.toml")` is the best approach, as it does not even allow using the `.docformatter.example.ini`.

**Comment by etimoz** [comment]
Unfortunately I can't provide any update either when this gets merged.

Yes, I provided the option now to specify a path to the config via the `--config` argument which should give more flexibility. When the config path is provided via the cmd line it does not look for any other config files. However, passing additional arguments via the command line should have priority over the config.

The old `.docformatter.example.ini` file I missed to remove, shouldn't be there in the first place as this should support [PEP-518](https://www.python.org/dev/peps/pep-0518/).

**Comment by fmigneault** [comment]
@etimoz 
Thanks for the quick update. I'm looking forward to this integration in a near future.

**Comment by rbowden91** [comment]
Currently, `_merge_run_options` seems to blow away all config options for me? The command line args all have default values (e.g., with no flags passed at the command line, `args.recursive` is `False`). So even if I specify `recursive = true` in `pyproject.toml`, `_merge_run_options` prioritizes the command line arguments (and their defaults), and so `merged_args['recursive']` is always `False`. Unless I specify `-r` at the command-line, which defeats the purpose.

**Comment by etimoz** [comment]
@rbowden91 you are right thanks. will look into it and fix it asap!

**Review by Borda — APPROVED** [review]

**Comment by weibullguy** [comment]
Closing as duplicate to already merged #77.

**Pull request closed without merging**
